### ISSUE TITLE
run SPIDER_local error

### ISSUE THREAD

**Issue by abrubru** [OpenState-SDN/openstate.p4#1]
when I tried to run ./run_demo.sh in SPIDER_local, I got the following information

Ready !
Traceback (most recent call last):
  File "topo.py", line 144, in <module>
    main()
  File "topo.py", line 135, in main
    makeTerm(net['s1'],title="Detect and Redirect node - Primary path/Detected link",cmd="tcpdump -n -i s1-eth2 -Uw - | tcpdump -en -r - vlan;echo;echo;echo Last command: \x1B[32m'tcpdump -n -i s1-eth2 -Uw - | tcpdump -en -r - vlan'\x1B[0m; bash")
TypeError: makeTerm() got an unexpected keyword argument 'cmd'
READY!!!

And there weren't xterm appeared, How to deal with it

**Comment by DavideSanvito** [comment]
Hi,
which version of Mininet are you using? Have you downloaded a clean Mininet 2.2.1 VM?
$ mn --version
2.2.1

**Comment by abrubru** [comment]
Hi,
Yes, I got the clean Mininet 2.2.1.VM.
$ mn --version
2.2.1d1
and i can run the mac_learning successfully

**Comment by DavideSanvito** [comment]
Hi,
I just downloaded a clean Mininet 2.2.1 VM (64 bit) and checked the version: it's 2.2.1.
Even after installing P4 it's still 2.2.1. Did you manually update Mininet?
I checked Mininet's GitHub repo but I cannot find the 2.2.1d1 version.

**Comment by abrubru** [comment]
Hi,
Yeah,I  updated Mininet manually, now I have solved  the problem and run your demo correctly.
Thanks.

**Comment by DavideSanvito** [comment]
Great!
