### ISSUE TITLE
dpctl stats-flow error

### ISSUE THREAD

**Issue by tnantha10** [OpenState-SDN/openstate.p4#2]
dpctl -c unix:/tmp/s1 stats-flow table=0 

the above returns and error when I tried running the p4 version of the portknocking code (~/openstate.p4/portknocking/run_demo).

It fails to create /tmp/s1 resulting in the failure.

Is there any other way to view stats-flow and stats-state?

**Comment by DavideSanvito** [comment]
Hi,
the main reason is that dpctl is a tool for OpenFlow switches, while openstate.p4 works with the behavioral model P4 switch. The dpctl stats-flow and stats-state can be only used against our OpenFlow softswitch https://github.com/OpenState-SDN/ofsoftswitch13 .
At http://schd.ws/hosted_files/2ndp4workshop2015/80/Politecnico%20di%20Milano,%20P4%20Workshop%20Nov%202015.pdf you can find some info about how we managed to define an OpenState-equivalent pipeline in P4.
Best,
Davide

**Comment by tnantha10** [comment]
Hi Davide,

Thanks very much for your response.
So I presume with this, there isn't a way to "watch" these tables live when traffic is injected (using the p4 behavioural switch)

**Comment by DavideSanvito** [comment]
Hi,
I'm sorry but I don't know if it's possible to query a P4 flow table, it's better if you ask on the P4 mailing list.
On the other hand a real state table does not exist in P4: we obtained an equivalent structure combining hash generator and registers. In this case it is possible to query the register by using the "register_read" command on the simple switch's CLI.
By the way if you are not tight to P4 and you are interested in experimenting with stateful processing in OpenFlow switches, I suggest you to try out our BEBA switch (https://github.com/beba-eu/beba-switch/).
BEBA switch includes all the features of OpenState (programable stateful packet forwarding), plus packet generation and it's even software accelerated. You can find more informations here http://www.beba-project.eu/.
Best,
Davide

**Comment by tnantha10** [comment]
Thanks very much Davide!
